SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio AS precio_euros, ROUND(precio * 1.0702945, 2) AS precio_dolares FROM producto;
SELECT nombre AS 'nom de producto', precio AS euros, ROUND(precio * 1.0702945, 2) AS 'dòlars' FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, UPPER(LEFT(nombre, 2)) FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, TRUNCATE(precio, 0) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT codigo_fabricante FROM producto GROUP BY codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante=2;
SELECT p.nombre, precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo;
SELECT p.nombre, precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo ORDER BY f.nombre ASC;
SELECT p.codigo AS 'código de producto', p.nombre AS 'nombre de producto', f.codigo AS 'código de fabricante', f.nombre AS 'nombre de fabricante' FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo;
SELECT p.nombre AS 'nombre de producto', precio, f.nombre AS 'nombre de fabricante' FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo ORDER BY precio ASC LIMIT 1;
SELECT p.nombre AS 'nombre de producto', precio, f.nombre AS 'nombre de fabricante' FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo ORDER BY precio DESC LIMIT 1;
SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Lenovo';
SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Crucial' AND precio > 200;
SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Asus' OR f.nombre='Hewlett-Packard' OR f.nombre='Seagate';
SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre AS 'nombre de producto', precio FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE LOWER(f.nombre) LIKE '%e'; 
SELECT p.nombre, precio FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE LOWER(f.nombre) LIKE '%w%';
SELECT p.nombre AS 'nombre de producto', precio, f.nombre AS 'nombre de fabricante' FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE PRECIO >= 180 ORDER BY precio DESC, p.nombre ASC;
SELECT f.codigo, f.nombre FROM fabricante f JOIN producto p ON p.codigo_fabricante=f.codigo GROUP BY f.codigo;
SELECT f.nombre AS 'fabricante', p.nombre AS 'producto' FROM fabricante f LEFT JOIN producto p ON p.codigo_fabricante=f.codigo;
SELECT f.nombre FROM fabricante f LEFT JOIN producto p ON p.codigo_fabricante=f.codigo WHERE p.nombre IS NULL;
SELECT p.nombre FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Lenovo';
SELECT p.nombre AS 'producto', precio, f.nombre AS 'fabricante' FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE precio=(SELECT MAX(precio) FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Lenovo');
SELECT p.nombre AS 'producto más caro' FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Lenovo' ORDER BY precio DESC LIMIT 1;
SELECT p.nombre AS 'producto más barato', precio FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Hewlett-Packard' ORDER BY precio ASC LIMIT 1;
SELECT p.nombre AS 'producto', precio, f.nombre AS 'fabricante' FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Asus' AND precio>=(SELECT MAX(precio) FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Lenovo');
SELECT p.nombre AS 'producto', precio, f.nombre AS 'fabricante' FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Asus' AND precio>=(SELECT AVG(precio) FROM producto LEFT JOIN fabricante f ON producto.codigo_fabricante=f.codigo WHERE f.nombre='Asus');