SELECT apellido1, apellido2, nombre FROM persona WHERE tipo='alumno' ORDER BY apellido1, apellido2, nombre ASC;
SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo='alumno' AND telefono IS NULL;
SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo='alumno' AND YEAR(fecha_nacimiento)=1999;
SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo='profesor' AND telefono IS NULL AND UPPER(nif) LIKE '%K';
SELECT nombre FROM asignatura WHERE cuatrimestre=1 AND curso=3 AND id_grado=7;
SELECT apellido1, apellido2, p.nombre, d.nombre FROM persona p JOIN profesor pr ON p.id=pr.id_profesor JOIN departamento d ON pr.id_departamento=d.id ORDER BY apellido1, apellido2, p.nombre ASC;
SELECT asig.nombre, anyo_inicio, anyo_fin FROM asignatura asig JOIN alumno_se_matricula_asignatura al_matr ON id_asignatura=asig.id JOIN persona p ON id_alumno=p.id JOIN curso_escolar ON al_matr.id_curso_escolar=curso_escolar.id WHERE UPPER(nif)='26902806M'; 
SELECT d.nombre FROM departamento d JOIN profesor pr ON id_departamento=d.id JOIN asignatura asig ON asig.id_profesor=pr.id_profesor JOIN grado ON grado.id=asig.id_grado WHERE grado.nombre='Grado en Ingeniería Informática (Plan 2015)' GROUP BY d.nombre;
SELECT p.nombre, apellido1, apellido2 FROM persona p JOIN alumno_se_matricula_asignatura al_matr ON id_alumno=p.id JOIN curso_escolar ON id_curso_escolar=curso_escolar.id WHERE anyo_inicio=2018 GROUP BY p.id;
SELECT d.nombre AS departamento, p.apellido1, p.apellido2, p.nombre FROM profesor prof RIGHT JOIN persona p ON p.id=prof.id_profesor LEFT JOIN departamento d ON prof.id_departamento=d.id ORDER BY d.nombre, apellido1, apellido2, p.nombre ASC;
SELECT apellido1, apellido2, p.nombre FROM persona p LEFT JOIN profesor pr ON p.id=pr.id_profesor WHERE id_departamento IS NULL; 
SELECT d.nombre, id_profesor FROM departamento d LEFT JOIN profesor pr ON d.id=pr.id_departamento WHERE id_profesor IS NULL; 
SELECT apellido1, apellido2, p.nombre FROM persona p LEFT JOIN profesor pr ON p.id=pr.id_profesor LEFT JOIN asignatura asig ON asig.id_profesor=pr.id_profesor WHERE asig.id_profesor IS NULL; 
SELECT asig.nombre FROM asignatura asig LEFT JOIN profesor pr ON asig.id_profesor=pr.id_profesor WHERE pr.id_profesor IS NULL;
SELECT d.nombre FROM departamento d LEFT JOIN profesor pr ON d.id=pr.id_departamento LEFT JOIN asignatura asig ON pr.id_profesor=asig.id_profesor GROUP BY d.nombre HAVING COUNT(asig.id)=0;
SELECT COUNT(p.id) AS total_alumnos FROM persona p WHERE p.tipo='alumno';
SELECT COUNT(p.id) AS numero_alumnos_1999 FROM persona p WHERE p.tipo='alumno' AND YEAR(fecha_nacimiento)=1999;
SELECT d.nombre, COUNT(id_profesor) AS numero_profesores FROM departamento d RIGHT JOIN profesor pr ON d.id=pr.id_departamento GROUP BY d.nombre ORDER BY numero_profesores DESC;
SELECT d.nombre, COUNT(id_profesor) AS numero_profesores FROM departamento d LEFT JOIN profesor pr ON d.id=pr.id_departamento GROUP BY d.nombre;
SELECT grado.nombre, COUNT(asig.id) AS numero_asignaturas FROM grado LEFT JOIN asignatura asig ON grado.id=asig.id_grado GROUP BY grado.nombre ORDER BY numero_asignaturas DESC;
SELECT grado.nombre, COUNT(asig.id) AS numero_asignaturas FROM grado RIGHT JOIN asignatura asig ON grado.id=asig.id_grado GROUP BY grado.nombre HAVING numero_asignaturas > 40 ORDER BY numero_asignaturas DESC;
SELECT grado.nombre, asig.tipo, SUM(asig.creditos) AS suma_creditos FROM grado LEFT JOIN asignatura asig ON grado.id=asig.id_grado GROUP BY grado.nombre, asig.tipo;
SELECT curso.anyo_inicio, COUNT(al_matr.id_alumno) AS numero_alumnos FROM alumno_se_matricula_asignatura al_matr RIGHT JOIN curso_escolar curso ON al_matr.id_curso_escolar=curso.id GROUP BY curso.anyo_inicio;
SELECT p.id, p.nombre, apellido1, apellido2, COUNT(asig.id) AS numero_asignaturas FROM persona p JOIN profesor pr ON p.id=pr.id_profesor LEFT JOIN asignatura asig ON pr.id_profesor=asig.id_profesor GROUP BY p.id ORDER BY numero_asignaturas DESC; 
SELECT * FROM persona p WHERE tipo='alumno' ORDER BY fecha_nacimiento DESC LIMIT 1; 
SELECT p.nombre, apellido1, apellido2 FROM persona p JOIN profesor pr ON p.id=pr.id_profesor JOIN departamento d ON pr.id_departamento=d.id LEFT JOIN asignatura asig ON pr.id_profesor=asig.id_profesor GROUP BY p.id HAVING COUNT(asig.id)=0;